### ISSUE TITLE
Ganglions now use a newer dongle: BLED112, not CSR dongle / Hub command change

### ISSUE THREAD

**Issue by wjcroft** [ChrisVeigl/BrainBay#16]
Chris, hi.

Since the fall of 2018, OpenBCI has dropped the old CSR dongles originally used with the Ganglion. This is because quite a few users were encountering problems with configuration of Zadig, and other issues.

The new dongle being shipped is the BLED112. Unfortunately there are probably hundreds of old CSR dongles in the field. So optimally BrainBay will be able to work with both. My guess is that this selection could be a dropdown in the Ganglion configuration box. "CSR" vs "BLED112" dongle type.

As far as your code change goes, it is just using the string "ble112" vs the original "ble" on line 323 of ob_ganglion.cpp. That tells the Hub what type of dongle you have.

Best regards, William

**Comment by wjcroft** [comment]
Oops, tabbed over the comment box on the original issue post. Just added that text.

Send me an email with your postal address and we can send you a BLED112 for your testing.

**Comment by abldvd** [comment]
Hello, I'm trying to connect  ganglion to BrainBay and I havea bluetooth csr dongle that works on the OpenBCI GUI but when I try to scan for the device in BrainBay it doesnt show anything.
 Is the CSR type dongle still supported in the new version?

**Comment by ChrisVeigl** [comment]
hi - there was a change in the communication protocol of the OpenBCI hub which probably broke the compatibility to Brainbay (also with the CSR dongle). we will investigate the issue ...

**Comment by abldvd** [comment]
Thanks for the quick answer. So if I downgrade the version of OpenBCI hub I use it should work right?

**Comment by wjcroft** [comment]
Abidvd, hi. Yes, if you drop back below version 2 of the Hub, it should work. I suggest if you use the OpenBCI_GUI, to drop that back to version compatible with the Hub. So both GUI and BrainBay can talk ok to the Hub.

**Comment by abldvd** [comment]
Perfect, thanks a lot. I dont know if I'll use the GUI too much, but for the moment I just downloaded the version of the Hub that I need in a separate folder from the one in the GUI, but I'll keep that in mind thanks
