### ISSUE TITLE
Dialog box: "ganglion connection error", with the contents, "Is the Ganglion board switched on and connected"

### ISSUE THREAD

**Issue by wjcroft** [ChrisVeigl/BrainBay#18]
Oddly, after installing this new 2.3.1 version, every time I start my design, I get a dialog box "ganglion connection error", with the contents, "Is the Ganglion board switched on and connected". Yes it is, I was just using it with the previous version of BrainBay (2.3). The Hub does get started.

When I access the Ganglion from the GUI, everything is working fine.

After the 2.3.1 install, I did re-enter the appropriate items into the Options panel, 200Hz and path,
C:\Program Files\OpenBCI_GUI\data\OpenBCIHub\OpenBCIHub.exe

I honestly can't see what I'm doing wrong. Should I have uninstalled first? I did not, I just installed over the old version.

I just did a complete uninstall followed by reinstall of 2.3.1. Same dialog box when starting the design.

**Comment by ChrisVeigl** [comment]
the connection procedure is probably not implemented optimally by now...
did you try to disconnect / connect the BLE dongle and select BLE112 for the ganglion's combo box again ?

it would help to see the debug output (start brainbay.exe  -d ,  e.g. from commandline).

**Comment by wjcroft** [comment]
Chris, thanks.

I did initially try unplugging and replugging the dongle. That made no difference.

But your suggestion of playing with the Ganglion element settings (right clicking on Ganglion), did eventually get it to work. It took several attempts still getting the dialog complaint. Finally I'm back online now and exiting / restarting my design finds it immediately.

Maybe I'll do a fresh install and turn on the debug. See if I can get a repeat failure.

Regards,

**Comment by Otemo** [comment]
I also have been seeing the same phenomena as the William's observation. I often try to connect several times. Usually, Brainbay successfully connects with ganglion board after two attempts.

**Comment by ChrisVeigl** [comment]
the connection procedure to the ganglion hub could definitely be improved. 
currently you need to follow a certain sequence to connect a new board
(select dongle CSR/BLE112, scan, select device, connect) - when you save the design is should automatically connect / play when you open it next time.

i will try to improve that as soon as i find some time ....
for now i'm glad that it works with both dongles - also if not 100% bullet proof   ;-)

anyhow - reports how connection errors can be reproduced are welcome !

**Comment by ChrisVeigl** [comment]
I tried to improve the connection state handling / processing of the OpenBCI messages. 
please try if it works better now...
this is not in a release package by now,
you could just replace the old brainBay.exe with the current one:
https://github.com/ChrisVeigl/BrainBay/blob/master/bin/brainBay.exe

**Comment by Otemo** [comment]
Thanks Chris.

I tried to connect the ganglion and Branbay with the new exe file. I did not find the error message.
It seems to work better...

**Comment by wjcroft** [comment]
Chris, hi. Both Otemo and I have tested your drop-in brainBay.exe (overlaid on top of the copy left by the 2.3.1 installer.) Works great. Go ahead and build your 2.3.2 installer.

Here is one guy commenting on the forum. I'll reply to him getting more details. I think he might have a strange dongle setup. As well as not putting the right default into Options / Applications Settings box. The sawtooth thing does not make any sense.

https://openbci.com/forum/index.php?p=/discussion/2097/ganglion-to-brainbay

By the way, on 2.3.2 could you update that Options / Applications Settings default? It should read:

C:\Program Files\OpenBCI_GUI\data\OpenBCIHub\OpenBCIHub.exe

That's where the Hub lives from last fall onward.

Much appreciation.

**Comment by ChrisVeigl** [comment]
okay great!
these changes will be released in the current version 2.4
