### ISSUE TITLE
best practice: get power of a bandwidth (smoothed) without display element

### ISSUE THREAD

**Issue by ElliotMebane** [ChrisVeigl/BrainBay#22]
I want to use a threshold with the power of a section of the bandwidth. 
I'm using Magnitude to isolate the SMR bandwidth then FFT to output Power. 
This requires the use of a FFT window that I don't want to display. 

Is there another way to access the power of a bandwidth (smoothed over N time)?

**Comment by ChrisVeigl** [comment]
I'm not sure if I understand correctly what you want to do ...
The magnitude element already calculates the power in passband and provides it at the output port.
see also demo design OtherDemos/magnitude_test.con

the fft element can also be used to calculate power in the selected freqeuncy range - alternatively to the magnitude element. 

adding on option to display/hide the fft graph is a good idea...
