### ISSUE TITLE
Cannot load library /NeurobitDrv.dll

### ISSUE THREAD

**Issue by Gratizest** [ChrisVeigl/BrainBay#26]
Hello, 
When I'm trying insert EEG amplifier block for Neurobit Optima 4, BrainBay throw \NeurobitRuntime\NeurobitDrv.dll. Does anyone have any ideas?

**Comment by ChrisVeigl** [comment]
where is your brainbay installation (the .exe file) located ?
is the .dll file present in the subfolder \NeurobitRuntime ?

**Comment by Gratizest** [comment]
Thanks for your respond. 
.exe is located in defoult location
.dll file is in right place
Everything is working fine now but i'm using older version.

**Comment by ChrisVeigl** [comment]
hmmm - then i have no idea what goes wrong... 
when i insert the neurobit element on my system, the .dll is loaded 
when pressing "change device configuration" in the parameter window, the neurobit settings window is displayed.
