### ISSUE TITLE
Muse - what is in the "other" output?

### ISSUE THREAD

**Issue by encoded-evolution** [ChrisVeigl/BrainBay#32]
There is an output "other" for Muse 2, what is in that output?  is that the extra electrode?

**Comment by ChrisVeigl** [comment]
i don't have a Muse-2, so i don't know ...  this is what the brainflow API returns.
it seems to be one of the "extended" channels - like timing / packet counter etc. - no physical biosignal.
I'd suggest to attach an oscilloscope element - maybe the data makes sense.

**Comment by encoded-evolution** [comment]
Heh, yes tried that didn't get anything.  I don't have an extra sensor, so maybe that's what its looking for.  Not sure.  BTW, the module works pretty good for the Muse.  I have been able to make several designs with it so far.

**Comment by ChrisVeigl** [comment]
alright!
BTW: would you like to share some designs ?

https://brainbay.iphpbb3.com/
would be a good place to do so :-)

**Comment by encoded-evolution** [comment]
@ChrisVeigl - I uploaded some designs and an edf to the forum.  Hope it is useful to someone.  Sorry if they are a bit messy.

**Comment by ChrisVeigl** [comment]
how cool!! thanks :-)
