### ISSUE TITLE
MIDI causing the app to stop?

### ISSUE THREAD

**Issue by encoded-evolution** [ChrisVeigl/BrainBay#33]
Although I am using a Muse 2, I am not sure that this issue has anything to do with the device or the driver per se - when I am fiddling around with MIDI settings to make the sounds come out best, suddenly Brainbay stops, often requiring a reset then hitting play again. 

Sometimes it *does require exiting the app entirely, and powering down/restarting the Muse.  But I haven't seen that so often.

I am guessing that it's the MIDI because that is the common factor when it happens.  Let me know if there's data that I could gather the next time. 

Windows 10, happens on a brand new desktop system and also on an ancient ASUS laptop.  Using a BLED dongle with the Muse 2

**Comment by ChrisVeigl** [comment]
I would be very surprised if the MIDI element causes this problem .... it is working very stable as far as i know ...

I suspect the BLE communication channel with the Muse device, and maybe something along the reception of the wireless data (probably noth within Brinbay code but within the Brainflow port handling).  but I don't know for sure.

Could you test if the problem still occursif you replace the Brainflow / Muse2 element with one (or multiple) Signal Generators ?

**Comment by encoded-evolution** [comment]
Now that I have played around with BrainBay more, I am inclined to agree that these issues are probably related to the BLE comms.  First, when replaced with EDF readers or signal generators as suggested, the issue does not surface.  Also, it seems to happen while wearing the headset for a live feed while designing and using my BT mouse... go figure.  You can close this issue.  Thanks

**Comment by ChrisVeigl** [comment]
ok - thanks for testing !
