### ISSUE TITLE
How to make a continuous Midi audio reward?

### ISSUE THREAD

**Issue by encoded-evolution** [ChrisVeigl/BrainBay#34]
Hi Chris,
I am experimenting creating various protocol designs, and many of these would require continuous audio rewards for eyes closed.  I have not been able to make a continuous, ongoing sound that would also trigger cleanly with a short burst reward.  I have attached an example file with an edf that has plenty of examples.  (The first few mins of the file are where the headset is "settling" and you can skip ahead by a minute or two)
The file also uses FFT for band isolation...just playing around with that, the settings are not finalized yet. :)
J
[Muse_EC_15min.zip](https://github.com/ChrisVeigl/BrainBay/files/9557672/Muse_EC_15min.zip)
[Muse_FR_incAlpSMR_3.zip](https://github.com/ChrisVeigl/BrainBay/files/9557676/Muse_FR_incAlpSMR_3.zip)

**Comment by encoded-evolution** [comment]
Never mind.... I discovered that the Midi "play only if note changes" checkbox does the trick

**Comment by ChrisVeigl** [comment]
hi! great that you found something that works for you!
If you really want a continuous sound feedback (not distinct midi notes) i suggest to use the "pitch" input of the midi element (and a suitable instrument which holds or loops the sound endlessly).
or you could use the sound player element which also allows continuous pitch(speed) and volume changes.

BTW: we could/should use the forum for such discussions: https://brainbay.iphpbb3.com/
