### ISSUE TITLE
Need examples of artifact filtering

### ISSUE THREAD

**Issue by encoded-evolution** [ChrisVeigl/BrainBay#36]
Are there examples to filter out artifacts from eye blinks or moving electrode cords?

I thought I might be able to use the meter/threshold for it, but could not figure out settings that worked.  
Filters either attenuate too much signal or produce too much ringing.

I was hoping to find a tool in Brain Bay to provide limits on microvolt spikes in the raw signal, but could not figure that out either.

Any help much appreciated

**Comment by ChrisVeigl** [comment]
You could probably use a combination of filtering (a bessel lowpass/bandpass / magnitude in the dominant frequency range of the muscle artifact) and the threshold/meter-element or logical elements (and/or) to mark these sections in a seperate channel in a multichannel EEG recording. You could also generate a "valid/invalid" indicator based on the detected level of EMG/EOG artifacts.  Unfortunately there are currently no examples for that in the brainbay distribution.

However, there are no possibilities in brainbay to timestamp these events (or insert timestamps in the history of a data stream / signal) or to remove eye-blink artifacts from affected EEG-channels (apart from FIR filtering).  For a professional artifact removal I recommend to record the signals to an edf file and then use dedicated tools or signal processing toolboxes, e.g in Matlab/Simulink.

Please use the brainbay forum for such questions.
https://brainbay.iphpbb3.com/

**Comment by encoded-evolution** [comment]
HI @ChrisVeigl  I posted a workable solution with an example over on the forum

**Comment by encoded-evolution** [comment]
@ChrisVeigl - Unfortunately, several posts I put on the forum are not showing, including one that responds to this with a solution.  Perhaps because they have attachments?  Not sure.

**Comment by ChrisVeigl** [comment]
indeed i have to admit posts with attachments - thanks for the reminder ! now your posts should be visible !
