### ISSUE TITLE
Muse 5th Electrode not recognized

### ISSUE THREAD

**Issue by encoded-evolution** [ChrisVeigl/BrainBay#37]
Hi @ChrisVeigl - I am using a 5th electrode with the Muse 2, but BrainBay does not recognize it.  Using an alternate app, I can see that the electrode is producing signal - so the Muse and electrode are ok.  

On the Brainflow website it appears that it should be supported.  Is this something that I have to enable with a config string, or does this require an update to the code?

**Comment by ChrisVeigl** [comment]
yes - the config string can be sent to the device - maybe th 5th channel can be activated this way...
but i never tried it because i have no device supportng this feature...

**Comment by encoded-evolution** [comment]
What is the syntax for that string?  When I insert it and then apply config, the app crashes

Sent via the Samsung Galaxy S8 Active, an AT&T 5G Evolution capable smartphone
Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by ChrisVeigl** [comment]
hi,

I'm sorry i cant help here because i don't have access to the HW...
I'd suggest to ask this question in the Brainflow forum or slack channel:

https://brainflow.readthedocs.io/en/stable/AskHelp.html
https://openbraintalk.slack.com/

**Comment by encoded-evolution** [comment]
Here is the solution: in the config string field in the EEG Brainflow biosignal compatable settings, type 

p50

that does the trick.

**Comment by ChrisVeigl** [comment]
nice! - thanks :)
