### ISSUE TITLE
massive brainflow_error_log.log created

### ISSUE THREAD

**Issue by pellet** [ChrisVeigl/BrainBay#40]
Under the CONFIGURATIONS\ directory brainflow_error_log.log file keeps being written out and filling up my hdd.
The file is reaching above 150GB in size and will keep increasing.
Any ideas on how to debug this issue and prevent the log file from being written out?

**Comment by ChrisVeigl** [comment]
oh wow! i have no idea why Brainflow fills up the file ...
do you use the Brainflow EEG element in your design(s) ?
why ist the content of the logfile (i suppose it's a repetion of the same message?)

BTW: you can delete the logfile (e.g. using a batch script which always deletes it after the Brainbay executable exits)

**Comment by pellet** [comment]
Yeah I use Cyton(BF) as the input.
I had trouble opening the file to see what the messages were, I'll try a 'tail command' on the file next time it happens.
One guess is that it could be because I switch off the Cyton while a session is running which causes Brainflow to keep logging error messages.
I currently have a small Brainflow log(<1MB) with lots of these messages:
`[board_logger] [debug] unable to read 1 byte`
If the Brainflow logging level was at warning instead of logging debug messages it could help.
For now i'll try not leaving BrainBay running in a bad connection state with the eeg device.

Thanks for the great work on BrainBay! it's been a nice user experience, using it for creating neurofeedback protocols and experiments.

**Comment by ChrisVeigl** [comment]
thank you for the positive feedback :-) 

It makes sense that a the reason for the massive error log output is a switched off device (when the session is still running) - this might create an error message every time a sample is expected (with sampling frequency!) - a lot of garbage indeed ;-)
I could try to change the logger initialisation from ´enable_dev_board_logger()´ to ´enable_board_logger()´  - see: https://brainflow.readthedocs.io/en/stable/UserAPI.html
Maybe this makes a difference...   

BTW: I have seen that you published your brainbay designs on your github account
https://github.com/pellet/brainbay-patches

this is great! - thanks a lot!  is there any documentation about the purpose and usage of these designs ? 
the user forum would be a good place to share those:
https://brainbay.iphpbb3.com/forum/88588673nx66966/brainbay-designs-and-experiences-f4/

**Comment by pellet** [comment]
Yeah if you use enable_board_logger it will stop the debug messages from coming through, so it will probably fix it.
If people are having issues with brainflow it might be resolved by looking through the repository issues and updating the library bundled in the app, otherwise could go further by exposing a `brainflow_debug_log=1` config setting.

Thanks for taking a look at the patches I've made, I put some links in there to papers and other info which helped guide my decisions.
I'll clean up the repository and remove the old patches I don't use anymore to make it a bit neater.
I'll add a bit more doco in there about the file naming convention, I think I'm using something close to standard neurofeedback notation now.
Once I do that i'll post to the BBS 👍

**Comment by ChrisVeigl** [comment]
i reduced the log level and released
https://github.com/ChrisVeigl/BrainBay/releases/tag/v2.8

**Comment by pellet** [comment]
@ChrisVeigl I've posted on the BrainBay forum regarding the patches I've created and the display/audio controllers which were used as feedback.
